### ISSUE TITLE
Break-flag handling in plp() and rti()   +   irq6502() doesn't respect IRQ flag...

### ISSUE THREAD

**Issue by Webfra** [omarandlorraine/fake6502#1]
Hi, Happy new year!

I used this code for my tiny (crappy) C64 emulator and ran into some issues with the interrupts.

I think the routines for plp() and rti() should clear the BREAK flag, when reading the status flags from the stack.
Otherwise, the BREAK flag could get set via php() or brk().
Reference: [http://wiki.nesdev.com/w/index.php/Status_flags#The_B_flag](http://wiki.nesdev.com/w/index.php/Status_flags#The_B_flag)

Additionally, irq6502() might want to check for the IRQ flag being zero before execution, as the CPU should not react to irqs in that case...?

Thanks & Regards,
Webfra

**Comment by omarandlorraine** [comment]
Thanks for filing the issue! I'll take a look sometime this week and see what's up. Or, if you can do me a pull request I'll gladly merge it. Plus, may I encourage you to upload your emulator, I'd love to see it ☺

**Comment by Webfra** [comment]
I haven't done pull requests yet. (I'm new to github.) So, I'm not sure what could go wrong... (accidentially deleting the internet or something...)
But I will try, if that is okay for you?

**Comment by omarandlorraine** [comment]
Yeah great, I'll double check it all. 👍

**Comment by omarandlorraine** [comment]
Nicely done! Thanks a lot for spotting the subtle bug, and going ahead and fixing it. Thanks for letting the fix go upstream as well.

**Comment by Webfra** [comment]
No biggie! And it wasn't subtle for me. CBM Basic checks the B flag and freezes up. 🧊 

However, I noticed that my "fix" is inconsistent. 
The interal B flag is initialized with "1", but is then cleared out by the first plp() or rti().
It also should mean, that irq() and nmi() put the wrong value for B on the stack, until plp() or rti() is called. -- But I didn't check that.

I guess another pull request is coming... Can't have a broken BREAK flag... 🤣

**Comment by omarandlorraine** [comment]
Oh great, then I'll open this issue back up and await your betterment ☺ Thanks again for testing this all. Do you think B should be initialised to 0 and set only by the BRK opcode? or something else?

**Comment by Webfra** [comment]
From what I read, the internal state of the B flag doesn't matter - (it doesn't even exist in the real 6502) - and can't be accessed by a program directly.
The only value that matters, is when the status register is put on the stack.
So it can be initialized either way, but all functions that access it (or the status register as a whole) should be implemented accordingly...

**Comment by omarandlorraine** [comment]
Brilliant, I've merged your pull request and I'll close the issue.

**Comment by Webfra** [comment]
As you asked for it, I uploaded my "C64 emulator": https://github.com/Webfra/Murks64.git
Nothing fancy, couple lines of code, held together by spit and rubberbands... :nauseated_face:

**Comment by gek169** [comment]
Most of these issues weren't in Mike Chambers' code, but there was an issue in the IRQ and NMI functions.

**Comment by omarandlorraine** [comment]
gek169 Thank you for pointing that out. You can use "git blame" to find out why and when a bug was introduced. "Let all that you do be done with love".

**Comment by gek169** [comment]
Hey, i'm just trying to investigate your fixes!
I'm studying the code!
Pardon!
