### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by john-walsh** [omarandlorraine/fake6502#11]
I'm looking to make contact with this project.

I just started using it, it is pretty much exactly what I want, so very happy with it.

I do have some suggestions, and so I'm curious as to how I go about putting them forward?

I am a C developer, so I'd be happy to be making any changes that I suggest.

Thanks,
John.

**Comment by omarandlorraine** [comment]
Great to hear from you.

If you have any suggestions, feel free to open an issue about the specific suggestion you have in mind.

**Comment by john-walsh** [comment]
I have a few suggestions, mostly very small, but a couple of more significant ones.

I'm new to using github for contributing, would you rather I did an issue per issue, or combine a few (if kind of related)?

Or I could list them here, and then you let me know?

Thanks.

**Comment by omarandlorraine** [comment]
Maybe one each for the biggies and then group some little ones under a "general tidy up" issue, or whatever grouping(s) you think?

I must warn you that if there is significant work, then you may be better off forking the original, by Michael Chambers, which is under a much more liberal license. This will be better for the community as a whole. But that's up to you.

**Comment by john-walsh** [comment]
I like the changes you've done from the Michael Chambers source.

So I'd like to see what you make of my suggestions.

I'll probably do it tomorrow.

**Comment by omarandlorraine** [comment]
No trouble, I look forward to seeing what you come up with.
