### ISSUE TITLE
first small changes

### ISSUE THREAD

**Issue by john-walsh** [omarandlorraine/fake6502#12]
Here are a couple of 'first' changes I'd like to make to the code.

I'm not trying to change any run-time functionality, or fix any bugs, it's just updating the source files to be more compliant with being a library/module that gets included within another project.

1) fake6502.c

 doxygen the header comment and include/update the version number to be a 'current' version.

2) fake6502.h

surround/protect the header file (from multiple includes) by:

```
#ifndef FAKE6502_H
#define FAKE6502_H
...
#endif
```

I hope these suggestions are not controversial, and if accepted, I'd like to edit the files and make the changes.

Please also then comment - how do I work with github?

Do I create a new branch (?) within this project, and then push my changes into my branch?

Thanks,
John.

**Comment by omarandlorraine** [comment]
Those are great ideas that should absolutely be included here. I look forward to it!

>Do I create a new branch (?) within this project, and then push my changes into my branch?

The easiest (and usual) way on github is if you fork the project. This will make a repo on your account, identical to mine. Here you can create a branch where you implement your changes. Then, after pushing, you can create a pull request from the feature branch on your repository into my repository.

**Comment by john-walsh** [comment]
OK, got it.

What version number do you want this branch to be/start at?

Are we 1.2 now, or should we bump it up to 2.0?

Remember, I've got more changes to suggest.


Oh, and one more suggestion for a change to the header file:

Adding the C++ wrapper:

#ifdef __cplusplus
extern "C" {
#endif

...

#ifdef __cplusplus
}
#endif

Personally, I don't use C++, but in the spirit of being a source code library, it should be accounted for.
