### ISSUE TITLE
bra() function miscalculates program counter?

### ISSUE THREAD

**Issue by Webfra** [omarandlorraine/fake6502#4]
Hi again, 
I think I found another issue.
For branches (relative jumps) the new program counter is calculated twice. Once in rel() and then again in bra(). In both places, the program counter is incremented. Therefore, the second calculation results in a wrong jump target address, as it reads the relative jump address from an already advanced PC.
rel() stores its result in c->ea, so I think bra() should just use the stored (and correct) value. 
Regards,
Webfra

**Comment by omarandlorraine** [comment]
Nicely done,
you found a bug, isolated it and fixed it.
I've gone ahead and merged your pull request.

I should probably get some kind of automatic tests running or something....

**Comment by gek169** [comment]
This bug is not in Mike Chambers' code.

**Comment by omarandlorraine** [comment]
gek169 Thank you for pointing that out. You can use "git blame" to find out why and when a bug was introduced. "Let all that you do be done with love".
